name: daily_tasks
description: A Flutter app for managing daily media consumption tasks
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.1

  # File system and path handling
  path_provider: ^2.1.1
  path: ^1.8.3
  file_picker: ^8.1.6
  permission_handler: ^11.3.1

  # Media playback
  video_player: ^2.8.1
  audioplayers: ^6.1.0

  # Widget support - using newer compatible version
  home_widget: ^0.6.0

  # UI and icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true